var CONSTANTS = {};

CONSTANTS.ACCESS_TOKEN_EXPIRY = "28800s"; //8hr 28800

CONSTANTS.ONE = 1;
CONSTANTS.TWO = 2;
CONSTANTS.THREE = 3;
CONSTANTS.FIVE = 5;
CONSTANTS.FOUR = 4;
CONSTANTS.SEVEN = 7;

//Feedback status
CONSTANTS.SUBMITTED = "Submitted";
CONSTANTS.WORKING = "Working";
CONSTANTS.RESOLVED = "Resolved";
CONSTANTS.WAITINGFORCONFIRMATION = "waitingForConfirmation";
CONSTANTS.NOTRESOLVED = "notResolved";
CONSTANTS.HOLD = "hold";
CONSTANTS.DELETED = "deleted";

//Task Status
CONSTANTS.PENDING = "Pending";
CONSTANTS.REJECTED = "Rejected";

CONSTANTS.ALL = "All";

module.exports = CONSTANTS;
